@base_url = http://localhost:5240

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST http://localhost:5240/funcionario/cadastrar
Content-Type: application/jsons


{
    "nome": "Seu nome",
    "cpf" : "12345678912"
}

### Obtenção de todos os funcionários
GET http://localhost:5240/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST http://localhost:5240/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 1000,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 1
}

### Obtenção de todas as folhas
GET http://localhost:5240/folha/listar

### Obtenção de uma folha
GET http://localhost:5240/folha/buscar/12345678912/10/2023